# Configuration file for ReadTheDocs

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - epub
