name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  security:
    name: Security scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        pip install -e ".[all]"
    
    - name: Run Bandit security scan
      run: |
        bandit -r genro_storage -f json -o bandit-report.json || true
        bandit -r genro_storage
      continue-on-error: true
    
    - name: Check dependencies with Safety
      run: |
        safety check --json --output safety-report.json || true
        safety check
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  complexity:
    name: Code complexity check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon
    
    - name: Calculate complexity
      run: |
        echo "## Cyclomatic Complexity" > complexity-report.md
        radon cc genro_storage -a -s >> complexity-report.md
        
        echo "" >> complexity-report.md
        echo "## Maintainability Index" >> complexity-report.md
        radon mi genro_storage >> complexity-report.md
        
        cat complexity-report.md
    
    - name: Upload complexity report
      uses: actions/upload-artifact@v5
      with:
        name: complexity-report
        path: complexity-report.md

  coverage-report:
    name: Detailed coverage report
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Start Docker services
      run: |
        docker compose up -d

        # Wait for critical services to be ready
        echo "Waiting for services to be ready..."

        # MinIO (required for S3 tests)
        timeout 90 bash -c 'until curl -f http://localhost:9000/minio/health/live 2>/dev/null; do echo "Waiting for MinIO..."; sleep 2; done'
        echo "✓ MinIO ready"

        # Azurite (optional - Azure tests)
        timeout 30 bash -c 'until nc -z localhost 10000 2>/dev/null; do echo "Waiting for Azurite..."; sleep 2; done' || echo "⚠ Azurite not ready (tests will skip)"

        # fake-gcs-server (optional - GCS tests)
        timeout 30 bash -c 'until curl -f http://localhost:4443/storage/v1/b 2>/dev/null; do echo "Waiting for fake-gcs-server..."; sleep 2; done' || echo "⚠ fake-gcs-server not ready (tests will skip)"

        # SFTP (optional - SFTP tests)
        timeout 30 bash -c 'until nc -z localhost 2222 2>/dev/null; do echo "Waiting for SFTP..."; sleep 2; done' || echo "⚠ SFTP not ready (tests will skip)"

        # SMB (optional - SMB tests)
        timeout 30 bash -c 'until nc -z localhost 445 2>/dev/null; do echo "Waiting for SMB..."; sleep 2; done' || echo "⚠ SMB not ready (tests will skip)"

        # WebDAV (optional - WebDAV tests)
        timeout 30 bash -c 'until curl -f http://localhost:8080 2>/dev/null; do echo "Waiting for WebDAV..."; sleep 2; done' || echo "⚠ WebDAV not ready (tests will skip)"

        echo "Service startup complete!"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[all,dev]"
        pip install coverage[toml]
    
    - name: Run tests with coverage
      env:
        MINIO_ENDPOINT: http://localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
      run: |
        pytest -v --cov=genro_storage --cov-report=term --cov-report=html --cov-report=json

    - name: Stop Docker services
      if: always()
      run: |
        docker compose down -v
    
    - name: Generate coverage badge
      run: |
        COVERAGE=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
        echo "Coverage: $COVERAGE%"
        
        # Create badge
        COLOR="red"
        if (( $(echo "$COVERAGE >= 80" | bc -l) )); then COLOR="green"; fi
        if (( $(echo "$COVERAGE >= 60 && $COVERAGE < 80" | bc -l) )); then COLOR="yellow"; fi
        
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        echo "BADGE_COLOR=$COLOR" >> $GITHUB_ENV
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v5
      with:
        name: coverage-reports
        path: |
          htmlcov/
          coverage.json
          coverage.xml
    
    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
