name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # MinIO (S3-compatible)
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

      # SFTP Server
      sftp:
        image: atmoz/sftp:latest
        ports:
          - 2222:22
        options: >-
          --health-cmd "pgrep sshd"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

      # Samba/SMB Server
      samba:
        image: dperson/samba:latest
        ports:
          - 139:139
          - 445:445
        env:
          USER: "testuser;testpass"
          SHARE: "share;/share;yes;no;no;testuser"
        options: >-
          --health-cmd "smbclient -L localhost -U testuser%testpass -m SMB3"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # WebDAV Server
      webdav:
        image: bytemark/webdav:latest
        ports:
          - 8080:80
        env:
          AUTH_TYPE: Basic
          USERNAME: testuser
          PASSWORD: testpass
        options: >-
          --health-cmd "curl -f http://localhost:80"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

      # Azurite (Azure Storage Emulator)
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite:latest
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
        options: >-
          --health-cmd "nc -z localhost 10000"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

      # fake-gcs-server (Google Cloud Storage Emulator)
      fake-gcs:
        image: fsouza/fake-gcs-server:latest
        ports:
          - 4443:4443
        options: >-
          --health-cmd "wget --spider -q http://localhost:4443/storage/v1/b"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Wait for services
      run: |
        echo "Waiting for services to be ready..."
        sleep 5

    - name: Run unit tests
      run: |
        pytest tests/ -v -m "not integration" --cov=genro_storage

    - name: Run integration tests
      run: |
        pytest tests/ -v -m integration --cov=genro_storage --cov-append

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
